CREATE TABLE IF NOT EXISTS book (
  id SERIAL PRIMARY KEY,
  isbn VARCHAR(100) UNIQUE,
  title VARCHAR(100) NOT NULL,
  author VARCHAR(100) NOT NULL);


CREATE TABLE IF NOT EXISTS book_instance (
  id SERIAL PRIMARY KEY,
  isbn VARCHAR(100) NOT NULL,
  book_id VARCHAR(100) UNIQUE,
  book_type VARCHAR(100) NOT NULL);
