services:
  postgres-catalog:
    image: postgres:16
    container_name: postgres-catalog
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5432
    volumes:
      - ./db/catalog:/var/lib/postgresql/data
      - ./catalog/src/main/resources/init.sql:/docker-entrypoint-initdb.d/catalog.sql
  postgres-lending:
    image: postgres:16
    container_name: postgres-lending
    restart: always
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5433
    volumes:
      - ./db/lending:/var/lib/postgresql/data
      - ./lending/src/main/resources/init.sql:/docker-entrypoint-initdb.d/lending.sql
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:latest
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
  catalog-app:
    image: chrisleed/library-catalog:latest
    container_name: catalog
    ports:
      - 8080:8080
    environment:
      POSTGRES_SERVER: postgres-catalog:5432
      POSTGRES_DATABASE: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres-catalog
      - kafka
      - zipkin
  lending-app:
    image: chrisleed/library-lending:latest
    container_name: lending
    ports:
      - 8081:8081
    environment:
      POSTGRES_SERVER: postgres-lending:5433
      POSTGRES_DATABASE: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres-lending
      - kafka
      - zipkin
